"""empty message

Revision ID: 05d515ced60c
Revises: d1573f858e07
Create Date: 2025-11-19 02:33:10.588170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d515ced60c'
down_revision: Union[str, Sequence[str], None] = 'd1573f858e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'total_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'total_cost',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'cost',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
