"""empty message

Revision ID: 07fcbfc33e24
Revises: 6b1046c5403b
Create Date: 2025-11-13 13:10:08.664681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fcbfc33e24'
down_revision: Union[str, Sequence[str], None] = '6b1046c5403b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referral_username', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'referral_username')
    # ### end Alembic commands ###
