"""empty message

Revision ID: 0c577d83a79e
Revises: e3e4c2813611
Create Date: 2025-11-19 08:46:35.306190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c577d83a79e'
down_revision: Union[str, Sequence[str], None] = 'e3e4c2813611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_referrer_balance')
    op.drop_column('users', 'total_premium')
    op.drop_column('users', 'total_stars')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_stars', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_premium', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_referrer_balance', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
