
"""empty message

Revision ID: 0d1fab8dac3b
Revises: d86870e3cf04
Create Date: 2025-11-13 11:50:47.288782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1fab8dac3b'
down_revision: Union[str, Sequence[str], None] = 'd86870e3cf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('referrals_referral_id_fkey'), 'referrals', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('referrals_referral_id_fkey'), 'referrals', 'users', ['referral_id'], ['telegram_id'])
    # ### end Alembic commands ###
