"""empty message

Revision ID: 52e33d9f4ed3
Revises: 1b358a1ba2dc
Create Date: 2025-11-19 17:13:27.755792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e33d9f4ed3'
down_revision: Union[str, Sequence[str], None] = '1b358a1ba2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'cost',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('referrals', 'earned_by_referrer',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('users', 'referrer_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referrer_balance',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('referrals', 'earned_by_referrer',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'cost',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
