"""empty message

Revision ID: 6b1046c5403b
Revises: 0d1fab8dac3b
Create Date: 2025-11-13 12:20:46.964585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1046c5403b'
down_revision: Union[str, Sequence[str], None] = '0d1fab8dac3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('earned_by_referrer', sa.Integer(), nullable=False))
    op.add_column('referrals', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('referrals', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('referrals', 'total_cash')
    op.drop_column('referrals', 'available_cash')
    op.drop_column('referrals', 'amount_ref')
    op.add_column('users', sa.Column('referrer_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_referrer_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_referrer_balance')
    op.drop_column('users', 'referrer_balance')
    op.add_column('referrals', sa.Column('amount_ref', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('available_cash', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('total_cash', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('referrals', 'updated_at')
    op.drop_column('referrals', 'created_at')
    op.drop_column('referrals', 'earned_by_referrer')
    # ### end Alembic commands ###
