"""empty message

Revision ID: 7f9c1e0566bf
Revises: d0bde89b6e5e
Create Date: 2025-11-30 06:16:15.152820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9c1e0566bf'
down_revision: Union[str, Sequence[str], None] = 'd0bde89b6e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'referral_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referral_username', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
