"""empty message

Revision ID: aa6999c13998
Revises: 7f9c1e0566bf
Create Date: 2025-11-30 10:30:52.209424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6999c13998'
down_revision: Union[str, Sequence[str], None] = '7f9c1e0566bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('referrals_referrer_id_fkey'), 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['referral_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('referrals_referrer_id_fkey'), 'referrals', 'users', ['referrer_id'], ['telegram_id'])
    # ### end Alembic commands ###
