"""empty message

Revision ID: d0bde89b6e5e
Revises: d496e2951af7
Create Date: 2025-11-22 01:14:04.824718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bde89b6e5e'
down_revision: Union[str, Sequence[str], None] = 'd496e2951af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('sender_id', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('recipient_username', sa.String(length=32), nullable=True))
    op.alter_column('payments', 'fragment_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['sender_id'], ['telegram_id'])
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['telegram_id'])
    op.alter_column('payments', 'fragment_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('payments', 'recipient_username')
    op.drop_column('payments', 'sender_id')
    # ### end Alembic commands ###
