"""empty message

Revision ID: d1573f858e07
Revises: 07fcbfc33e24
Create Date: 2025-11-19 02:27:11.292200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1573f858e07'
down_revision: Union[str, Sequence[str], None] = '07fcbfc33e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.add_column('payments', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('payments', sa.Column('product', sa.String(length=32), nullable=True))
    op.add_column('payments', sa.Column('amount', sa.String(length=16), nullable=True))
    op.add_column('payments', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['telegram_id'])
    op.drop_column('payments', 'crypto_asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('crypto_asset', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'update_at')
    op.drop_column('payments', 'amount')
    op.drop_column('payments', 'product')
    op.drop_column('payments', 'user_id')
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('purchases_payment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('purchases_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchases_pkey'))
    )
    # ### end Alembic commands ###
