"""empty message

Revision ID: d496e2951af7
Revises: 52e33d9f4ed3
Create Date: 2025-11-21 23:40:51.905866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd496e2951af7'
down_revision: Union[str, Sequence[str], None] = '52e33d9f4ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('fragment_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'fragment_id')
    # ### end Alembic commands ###
