"""empty message

Revision ID: e3e4c2813611
Revises: b9d8da6d31db
Create Date: 2025-11-19 06:09:05.810312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e4c2813611'
down_revision: Union[str, Sequence[str], None] = 'b9d8da6d31db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="amount::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True,
                )
    # ### end Alembic commands ###
